### PR TITLE
Modernized PHP code and type safe options class

### PR DESCRIPTION
**Pull request by phpfui**
This is a modernized version of the PHP library.  Here are some of the features:

* Still PHP 5.3 compatible
* Added composer.json for packagist.org
* Added namespaces and untangled classes and files.
* Removed unused PHP code.
* Added fully type safe PHP configuration option classes (see designer and viewer.php)
* Made code autoload compatible, PSR-4
* Added unit tests for options
* Added code generator for options (although some hand edits may be needed and constants could be added).
* Created a public directory with only public files (PHPUnit should not be public for example).
* Removed PHPMailer from repo, now included via composer
* Added Mailer interface (but not really required) and getMailer method so another mailer could be used if it implements the PHPMailer interface.

Possible To Do's:
 * Create Packagist.org account and add this repo.  This will make it easier for users to install.
 * Possibly modify README.md to explain that the user should modify autoload.php to their autoloader.
 * Possible renaming of Option classes to better match the JavaScript classes.
 * Testing on various versions of PHP.  Seems to run under PHP 8.0 and option classes work under 5.3.
 * Add install script for installs made via composer

Let me know of any questions or concerns.

### CODE REVIEW

**Comment by phpfui** [comment]
Another thing that will need to be changed to support PHP 7.0 and higher is all the try catch blocks.

You will need to catch Throwable first (PHP 7.0 and higher), then Exception.  PHP 7 and higher will not catch many errors with just Exception.  This is mostly in the SQL adapters.  I fixed the MySQL adapter, but not the others.  Ideally the PDO code should be in a base class, as it should be all the same.  If I have time, I may be able to add that refactor.

More details here: https://www.php.net/manual/en/language.errors.php7.php

**Comment by phpfui** [comment]
Refactored PDO code into SQLAdapter class and removed most of the duplicate code from the specific instances.  If you decide to merge, you can take the master branch of all files but *.php.  Also added more unit tests for the PDO classes.

**Comment by VladimirHot** [comment]
Thank you very much for your improvements, they formed the basis of our packages. Although a lot of time has passed. You can find them at the link below:

https://packagist.org/packages/stimulsoft/

**Comment by phpfui** [comment]
Glad you could use it. The project I was on that needed this got cancelled, but I will revisit if I ever need something like this.

**Pull request closed without merging**
